services:
  # Web Service
  - type: web
    name: gcse-progress-tracker
    runtime: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn config.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.5
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        sync: false
      - key: ANTHROPIC_API_KEY
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: gcse-tracker-db
          property: connectionString
      - key: SITE_URL
        sync: false
      - key: CSRF_TRUSTED_ORIGINS
        sync: false

databases:
  # PostgreSQL Database
  - name: gcse-tracker-db
    plan: free
    databaseName: gcse_tracker
    user: gcse_user